### ISSUE TITLE
Create new entity/account data class(es) to accommodate patron aggregation

### ISSUE THREAD

**Issue by ncovercash** [ualibweb/mod-data-export-worker#60]

**Comment by nhanaa** [comment]
@ncovercash This issue should be done by this commit: [https://github.com/ualibweb/mod-data-export-worker/commit/00249e0fa38d1cc8c3a152d7f83e768d451a54bd](https://github.com/ualibweb/mod-data-export-worker/commit/00249e0fa38d1cc8c3a152d7f83e768d451a54bd)

**Comment by ncovercash** [comment]
@nhanaa lgtm
